export const SUMMARY_LIST_REQUESTED = 'SUMMARY_LIST_REQUESTED';
export const SUMMARY_LIST_SUCCESS = 'SUMMARY_LIST_SUCCESS';
export const SUMMARY_LIST_FAILURE = 'SUMMARY_LIST_FAILURE';

export const HISTORY_REQUESTED = 'HISTORY_REQUESTED';
export const HISTORY_SUCCESS = 'HISTORY_SUCCESS';
export const HISTORY_FAILURE = 'HISTORY_FAILURE';
